version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: transaction-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/my_data
    restart: unless-stopped